var 
    c1 = document.getElementById('input-file'),
    c2 = document.getElementById('save-mesh'),
    c3 = document.getElementById('message'),
    c4 = document.getElementById('bottom-nav-bar'),
    c5 = document.getElementById('close'),
    c6 = document.getElementById('load-file'),
    c7 = document.getElementById('file-name'),
    c8 = document.getElementById('select-mesh'),
    c9 = document.getElementById('msg-select-mesh'),
    c10 = document.getElementById('delete-mesh'),
    c11 = document.getElementById('bnb-zoom'),
    c12 = document.getElementById('bnb-rotate'),
    c13 = document.getElementById('bnb-move'),
    c14 = document.getElementById('bnb-add'),
    c15 = document.getElementById('bnb-edit'),
    c16 = document.getElementById('bnb-delete'),
    c17 = document.getElementById('bfc-checkbox'),
    c18 = document.getElementById('polygon-list'),
    c19 = document.getElementById('bnb-change-color'),
    c20 = document.getElementById('input-change-color-mesh'),
    c21 = document.getElementById('container-point-polygon'),
    c22 = c21.querySelectorAll('input[type=text]'),
    c23 = c18.querySelector('ul'),
    c24 = document.getElementById('enter-point-polygon'),
    myCanvas = document.getElementById('canvas'),
    selectedMeshColor = "#333333",
    isBFCEnabled = false,
    isPolygonPointUpdate = false,
    prevPolygonPoints,
    file = null,
    scene,
    meshCtrld, 
    sortedList, 
    camera, 
    render,
    liVal,
    choosePoly,
    currentStateElement = null
