var 
    c1 = document.getElementById('input-file'),
    c2 = document.getElementById('save-mesh'),
    c3 = document.getElementById('message'),
    c4 = document.getElementById('bottom-nav-bar'),
    c5 = document.getElementById('close'),
    c6 = document.getElementById('load-file'),
    c7 = document.getElementById('file-name'),
    c8 = document.getElementById('select-mesh'),
    c9 = document.getElementById('msg-select-mesh'),
    c11 = document.getElementById('bnb-zoom'),
    c12 = document.getElementById('bnb-rotate'),
    c13 = document.getElementById('bnb-move'),
    c14 = document.getElementById('bnb-add'),
    c15 = document.getElementById('bnb-edit'),
    c16 = document.getElementById('bnb-delete'),
    file = null,
    currentStateElement = null